# Generated by Django 4.2 on 2024-10-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
