# Generated by Django 4.2 on 2024-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_precio_total_venta_total_venta_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciodinamico',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='nombre_regla',
            field=models.CharField(default='Regla Predeterminada', max_length=255),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='prioridad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preciodinamico',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preciodinamico',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preciodinamico',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
