# Generated by Django 4.2 on 2024-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_fecha_movimiento_movimientocliente_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MovimientoCliente',
        ),
    ]
