# Generated by Django 4.2 on 2024-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_cliente_ciudad_cliente_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaservicio',
            name='horarios',
            field=models.CharField(blank=True, help_text='Ingresa los horarios disponibles separados por comas. Ejemplo: 14:00, 15:30, 17:00', max_length=200),
        ),
    ]
