# Generated by Django 4.2 on 2024-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_preciodinamico_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='duracion_reserva_unidad',
            field=models.CharField(blank=True, choices=[('minuto', 'Minuto'), ('hora', 'Hora'), ('dia', 'Día')], help_text='Unidad de tiempo para la reserva.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='duracion_reserva_valor',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de tiempo para la reserva.', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='duracion_reserva',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
