# Generated by Django 4.2 on 2024-10-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_categoriaservicio_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('webpay', 'WebPay'), ('descuento', 'Descuento'), ('giftcard', 'GiftCard'), ('flow', 'FLOW'), ('mercadopago', 'MercadoPago'), ('scotiabank', 'ScotiaBank'), ('bancoestado', 'BancoEstado'), ('cuentarut', 'CuentaRut')], max_length=100),
        ),
    ]
