# Generated by Django 4.2 on 2024-09-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agendamiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.categoriaproducto')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='duracion_reserva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='es_reservable',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='es_externo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='reservaproducto',
            name='fecha_agendamiento',
        ),
        migrations.RemoveField(
            model_name='ventareserva',
            name='productos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservaproducto',
            name='venta_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaproductos', to='ventas.ventareserva'),
        ),
        migrations.DeleteModel(
            name='PrecioDinamico',
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.servicio'),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='venta_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaservicios', to='ventas.ventareserva'),
        ),
        migrations.AddField(
            model_name='movimientocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        ),
    ]
