# Generated by Django 4.2 on 2024-09-27 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_producto_duracion_reserva_unidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='preciodinamico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='categoriaproducto',
            name='ventas_cate_nombre_389748_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='ventas_clie_nombre_134519_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientocliente',
            name='ventas_movi_fecha_79f526_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='ventas_pago_venta_i_281a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='preciodinamico',
            name='ventas_prec_tipo_re_c54c42_idx',
        ),
        migrations.RemoveIndex(
            model_name='preciodinamico',
            name='ventas_prec_fecha_i_10393f_idx',
        ),
        migrations.RemoveIndex(
            model_name='preciodinamico',
            name='ventas_prec_fecha_f_065c70_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='ventas_prod_nombre_c9f126_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='ventas_prod_precio__9c7ebb_idx',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='ventas_rese_product_c040e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_fecha_v_357f1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='ventas_vent_cliente_d44864_idx',
        ),
        migrations.RenameField(
            model_name='movimientocliente',
            old_name='fecha',
            new_name='fecha_movimiento',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_fin',
            new_name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='categoriaproducto',
            name='tipo_duracion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='preciodinamico',
            name='tipo_regla',
        ),
        migrations.RemoveField(
            model_name='preciodinamico',
            name='valor_regla',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='duracion_reserva_unidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='duracion_reserva_valor',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preciodinamico',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcialmente Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='tipo_movimiento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('webpay', 'WebPay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preciodinamico',
            name='nombre_regla',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='duracion_reserva',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaprodutos', to='ventas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='productos',
            field=models.ManyToManyField(through='ventas.ReservaProducto', to='ventas.producto'),
        ),
    ]
