# Generated by Django 4.2 on 2024-09-30 03:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_movimientocliente_reservaservicio_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocliente',
            name='fecha_movimiento',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=7200)),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=7200)),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='productos',
            field=models.ManyToManyField(through='ventas.ReservaProducto', to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='servicios',
            field=models.ManyToManyField(through='ventas.ReservaServicio', to='ventas.servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='tipo_movimiento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_agendamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
