# Generated by Django 4.2 on 2024-09-30 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_movimientocliente_reservaservicio_servicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientocliente',
            old_name='fecha_movimiento',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='productos',
            field=models.ManyToManyField(blank=True, through='ventas.ReservaProducto', to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, through='ventas.ReservaServicio', to='ventas.servicio'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=656564, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientocliente',
            name='tipo_movimiento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
