# Generated by Django 4.2 on 2024-09-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_reservaproducto_alter_preciodinamico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.reserva'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('paypal', 'PayPal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.reserva'),
        ),
        migrations.DeleteModel(
            name='PrecioDinamico',
        ),
    ]
