# Generated by Django 4.2 on 2024-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_cliente_documento_identidad_ventareserva_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventareserva',
            name='numero_documento_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
