# Generated by Django 4.2 on 2024-10-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0016_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventareserva',
            name='estado',
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='cobrado',
            field=models.BooleanField(default=False, verbose_name='Cobrado'),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='codigo_giftcard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código GiftCard'),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcialmente Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='ventareserva',
            name='estado_reserva',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('checkin', 'Check-in'), ('checkout', 'Check-out')], default='pendiente', max_length=10, verbose_name='Estado de Reserva'),
        ),
        migrations.AlterField(
            model_name='ventareserva',
            name='fecha_reserva',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Venta Reserva'),
        ),
    ]
