# Generated by Django 4.2 on 2024-10-28 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0017_remove_ventareserva_estado_pago_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
    ]
