# Generated by Django 4.2 on 2024-11-03 02:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_compra_remove_proveedor_contacto_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('monto_inicial', models.DecimalField(decimal_places=0, max_digits=10)),
                ('monto_disponible', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('por_cobrar', 'Por Cobrar'), ('cobrado', 'Cobrado')], default='por_cobrar', max_length=10)),
                ('cliente_comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_compradas', to='ventas.cliente')),
                ('cliente_destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_recibidas', to='ventas.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='giftcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.giftcard'),
        ),
    ]
