# Generated by Django 4.2 on 2024-11-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_alter_compra_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('checkin', 'Check-in'), ('checkout', 'Check-out')], default='pendiente', max_length=10, verbose_name='Estado de Servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('efectivo', 'Efectivo'), ('webpay', 'WebPay')], max_length=50),
        ),
    ]
